### ISSUE TITLE
Nav menu behind Map or Tilelayer

### ISSUE THREAD

**Issue by mhcpan** [OriginalSin/svelte-leaflet#1]
The nav menu will be shown behind Map or Tilelayer if broswer width is reduced.

![image](https://user-images.githubusercontent.com/2284901/84340293-f3346300-abd2-11ea-83de-79c78aacd369.png)

**Comment by OriginalSin** [comment]
Fixed Map and Tilelayer display.

**Comment by mhcpan** [comment]
Hi,
When view from the phone, it now shows grey nav menu and cannot select the
items.
